### ISSUE TITLE
Tennis court surface types

### ISSUE THREAD

**Issue by stuartmccarroll** [openactive/facility-types#3]
We operate Grass, Clay and Hard court. Although I'm sure other may need artificial grass as well.

We have built that into the activity description for now.

**Comment by nickevansuk** [comment]
Thank you for for feedback! This has been addressed by https://github.com/openactive/facility-types/issues/1#issuecomment-1153929202.

The associated controlled vocabulary now includes `Grass`, `Hard (Macadam)`, and `Clay` related to `Tennis Court`. It also includes: `Rubber Crumb Artificial Grass`, `Sand Based Artificial Grass`, `Water Based Artificial Grass`.

Please do open another issue at https://github.com/openactive/facility-attribute-list/issues for any further feedback, which is always welcomed and appreciated.
